name: Revert Test Branch

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Test Branch
        uses: actions/checkout@v4
        with:
          ref: test
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "paripuranam"
          git config user.email "paripuranam333@gmail.com"

      - name: Revert Last Commit
        run: |
          git revert HEAD --no-edit

      - name: Add Skip CI
        run: |
          git commit --amend -m "Rollback from Jira [skip ci]"

      - name: Push Changes
        run: |
          git push origin test
