name: Jira Trigger Pipeline
#Testing
on:
  workflow_dispatch:
    inputs:
      issue:
        required: true
      status:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Jira Details
        run: |
          echo "Triggered from Jira"
          echo "Issue Key: ${{ github.event.inputs.issue }}"
          echo "Status: ${{ github.event.inputs.status }}"

      - name: Run Pipeline
        run: |
          echo "Pipeline started automatically"
